---
kind: BuildConfig
apiVersion: v1
metadata:
  name: ansible-lint-base
  labels:
    name: ansible-lint-base
spec:
  triggers:
  - type: Generic
    generic:
      secret: "secret101"
  - type: "GitHub"
    github:
      secret: "secret101"
  - type: ConfigChange
  output:
    to:
      kind: ImageStreamTag
      name: "ansible-lint-base:latest"
  source:
    type: Git
    git:
      uri: https://github.com/godleon/learning_openshift
      ref: "master"
    contextDir: "examples/ansible-lint-s2i_base-image"
  strategy:
    type: Source
    sourceStrategy:
      from:
        kind: ImageStreamTag
        name: python-35-centos7:latest
      env:
      - name: "UPGRADE_PIP_TO_LATEST"
        value: "true"
