kind: DeploymentConfig
apiVersion: v1
metadata:
  name: run-ansible-lint
spec:
  strategy:
    type: Rolling
    rollingParams:
      updatePeriodSeconds: 1
      intervalSeconds: 1
      timeoutSeconds: 120
  triggers:
  - type: ImageChange
    imageChangeParams:
      automatic: true
      containerNames:
      - run-ansible-lint-helloworld
      from:
        kind: ImageStreamTag
        name: ansible-lint-sample:latest
  - type: ConfigChange
  # replicas: 1
  # selector:
  #   name: frontend
  template:
    metadata:
      labels:
        name: run-ansible-lint
    spec:
      containers:
      - name: run-ansible-lint-helloworld
        image: " "
        ports:
        - containerPort: 8080
          protocol: TCP
        resources:
          limits:
            memory: "512Mi"
        terminationMessagePath: "/dev/termination-log"
        imagePullPolicy: IfNotPresent
        securityContext:
          capabilities: {}
          privileged: false
      # restartPolicy: Always
      dnsPolicy: ClusterFirst