kind: BuildConfig
apiVersion: v1
metadata:
  name: sample-pipeline
  labels:
    name: sample-pipeline
spec:
  triggers:
  - type: Generic
    generic:
      secret: secret101
  strategy:
    type: JenkinsPipeline
    jenkinsPipelineStrategy:
      jenkinsfile: |-
        node('maven') {
          stage 'build'
          openshiftBuild(buildConfig: 'bc1', showBuildLogs: 'true')
          stage 'deploy'
          openshiftDeploy(deploymentConfig: 'frontend')
        }