kind: BuildConfig
apiVersion: v1
metadata:
  name: sample-pipeline
  labels:
    name: sample-pipeline
spec:
  triggers:
  - type: Generic
    generic:
      secret: secret101
  strategy:
    type: JenkinsPipeline
    jenkinsPipelineStrategy:
      jenkinsfilePath: "examples/pipeline-helloworld/parallel.groovy"