kind: BuildConfig
apiVersion: v1
metadata:
  name: pipeline-parallel
  # labels:
  #   name: pipeline-parallel
spec:
  triggers:
  - type: Generic
    generic:
      secret: secret101
  source:
    type: "Git"
    git:
      uri: "https://github.com/godleon/learning_openshift"
      ref: "master"
  strategy:
    type: JenkinsPipeline
    jenkinsPipelineStrategy:
      jenkinsfilePath: "examples/pipeline-helloworld/parallel.groovy"