---
kind: BuildConfig
apiVersion: v1
metadata:
  name: ansible-lint-docker
  labels:
    name: ansible-lint-docker-build
spec:
  triggers:
  - type: Generic
    generic:
      secret: secret101
  # output:
  #   to:
  #     kind: ImageStreamTag
  #     name: "ansible-lint-docker:latest"
  source:
    type: Git
    git:
      uri: https://github.com/godleon/learning_openshift
      ref: "master"
    contextDir: "examples/ansible-lint-docker"
  strategy:
    type: Docker
    dockerStrategy:
      # noCache: true
      dockerfilePath: Dockerfile
