---
kind: BuildConfig
apiVersion: v1
metadata:
  name: ansible-lint
  labels:
    name: ansible-lint-build
spec:
  triggers:
  - type: Generic
    generic:
      secret: secret101
  output:
    to:
      kind: ImageStreamTag
      name: "ansible-lint:latest"
  source:
    type: Git
    git:
      uri: https://github.com/godleon/learning_openshift
      ref: "master"
    contextDir: "examples/ansible-lint-s2i"
  strategy:
    type: Source
    sourceStrategy:
      from:
        kind: ImageStreamTag
        name: python-35-centos7:latest
      # env:
      # - name: "UPGRADE_PIP_TO_LATEST"
      #   value: "true"
