kind: DeploymentConfig
apiVersion: v1
metadata:
  name: my-ansible-lint
spec:
  strategy:
    type: Rolling
    # rollingParams:
    #   updatePeriodSeconds: 1
    #   intervalSeconds: 1
    #   timeoutSeconds: 120
  triggers:
  - type: ImageChange
    imageChangeParams:
      automatic: false
      containerNames:
      - run-my-ansible-lint
      from:
        kind: ImageStreamTag
        # name: my-ansible-lint:latest
        name: ansible-lint-base:latest
  # - type: ConfigChange
  replicas: 1
  # selector:
  #   name: frontend
  template:
    metadata:
      labels:
        name: run-my-ansible-lint
    spec:
      containers:
      - name: run-my-ansible-lint
        image: 172.30.255.36:5000/ansible-lint/ansible-lint-base:latest
      #   ports:
      #   - containerPort: 8080
      #     protocol: TCP
        resources:
          limits:
            memory: "512Mi"
        # terminationMessagePath: "/dev/termination-log"
        imagePullPolicy: IfNotPresent
        securityContext:
          capabilities: {}
          privileged: false
      # restartPolicy: Always
      dnsPolicy: ClusterFirst