kind: BuildConfig
apiVersion: v1
metadata:
  name: hello-pipeline
spec:
  source:
    type: "Git"
    git:
      uri: "https://github.com/godleon/learning_openshift.git"
      ref: "master"
    contextDir: "jenkins_pipeline"
  strategy:
    type: JenkinsPipeline
    jenkinsPipelineStrategy:
      jenkinsfilePath: "hello-pipeline.groovy"
      